openapi: 3.0.0
info:
  title: Movements
  description:
    This application allows you to obtain the movements of a client and their products.
  version: 1.0.0
externalDocs:
  description: Find out more about Customer Movements
  url: http://swagger.io
servers:
  - url: https://localhost:8084
tags:
  - name: movements
    description: Everything about your movements
paths:
  /movement/customer/{clientId}/account/{accountNumber}:
    get:
      tags:
        - movements
      summary: It allows to obtain the movements of a client's account.
      description: Allows you to obtain all the movements of a client's account, with a range of dates (optional)
      operationId: movementsByAccount
      parameters:
        - name: clientId
          in: path
          description: ID of the customer.
          required: true
          schema:
            type: string
        - name: accountNumber
          in: path
          description: Customer account number
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movements'
        '400':
          description: Invalid request
        '404':
          description: Customer Id or Account number are invalid

  /movement/customer/{clientId}/credit/{creditNumber}:
    get:
      tags:
        - movements
      summary: It allows to obtain the movements of a client's credits.
      description: Allows you to obtain all the movements of a client's credits, with a range of dates (optional)
      operationId: movementsByCredit
      parameters:
        - name: clientId
          in: path
          description: ID of the customer.
          required: true
          schema:
            type: string
        - name: creditNumber
          in: path
          description: Customer credit number
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movements'
        '400':
          description: Invalid request
        '404':
          description: Customer Id or Credit number are invalid

  /movement/customer/{clientId}/card/{cardNumber}:
    get:
      tags:
        - movements
      summary: It allows to obtain the movements of a client's cards.
      description: Allows you to obtain all the movements of a client's cards, with a range of dates (optional)
      operationId: movementsByCard
      parameters:
        - name: clientId
          in: path
          description: ID of the customer.
          required: true
          schema:
            type: string
        - name: cardNumber
          in: path
          description: Customer card number
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movements'
        '400':
          description: Invalid request
        '404':
          description: Customer Id or Credit number are invalid

  /movement:
    post:
      tags:
        - movements
      summary: It allows you to save a movement of your credit
      operationId: saveMovement
      requestBody:
        required: true
        description: Allows you to save information about your credit.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movements'
      responses:
        '200':
          description: OK


components:
  schemas:
    SaveMovements:
      type: object
      properties:
        amount:
          type: number
          format: double
        clientDocument:
          type: string
        creditNumber:
          type: string
        movementType:
          type: string

    Movements:
      type: object
      properties:
        movementNumber:
          type: string
          description: Movement number
        movementType:
          type: string
          description: Type of Movement
        clientDocument:
          type: string
          description: Customer Document
        accountType:
          type: string
          description: Type of account
        accountNumber:
          type: string
          description: Account Number
        cardNumber:
          type: string
          description: Card Number
        creditNumber:
          type: string
          description: Credit ID
        amount:
          type: number
          format: double
        commission:
          type: number
          format: double
        movementDate:
          type: string
          format: date
            
      